// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFIqqnchOL8Bggbij8jTEee47hHTWSl7c',
    appId: '1:810065522962:web:97952eb2ab61ab8ce583cb',
    messagingSenderId: '810065522962',
    projectId: 'puzzle-app-72bef',
    authDomain: 'puzzle-app-72bef.firebaseapp.com',
    storageBucket: 'puzzle-app-72bef.firebasestorage.app',
    measurementId: 'G-EQWCRVWBVK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW1Xd94j7RgYgtVrN_vSMzkJyyKw8Tlgk',
    appId: '1:810065522962:android:548018c8e214547ee583cb',
    messagingSenderId: '810065522962',
    projectId: 'puzzle-app-72bef',
    storageBucket: 'puzzle-app-72bef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXBpbRUCYT0QG-oTkzCJo7FYM1Sgqs8Zs',
    appId: '1:810065522962:ios:5d47b6ae169292fde583cb',
    messagingSenderId: '810065522962',
    projectId: 'puzzle-app-72bef',
    storageBucket: 'puzzle-app-72bef.firebasestorage.app',
    iosBundleId: 'com.example.puzzelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXBpbRUCYT0QG-oTkzCJo7FYM1Sgqs8Zs',
    appId: '1:810065522962:ios:5d47b6ae169292fde583cb',
    messagingSenderId: '810065522962',
    projectId: 'puzzle-app-72bef',
    storageBucket: 'puzzle-app-72bef.firebasestorage.app',
    iosBundleId: 'com.example.puzzelApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFIqqnchOL8Bggbij8jTEee47hHTWSl7c',
    appId: '1:810065522962:web:48ad668d9b2fbca6e583cb',
    messagingSenderId: '810065522962',
    projectId: 'puzzle-app-72bef',
    authDomain: 'puzzle-app-72bef.firebaseapp.com',
    storageBucket: 'puzzle-app-72bef.firebasestorage.app',
    measurementId: 'G-YVVR4DBGQ7',
  );
}
